### ISSUE TITLE
Examples build fails on M1 Mac

### ISSUE THREAD

**Issue by hariria** [AmbientRun/Ambient#234]
I keep getting 
```bash
[2023-03-18T16:31:34Z INFO  ambient] Building Tic Tac Toe
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: no compiler-artifact', /Users/andrewhariri/.cargo/git/checkouts/ambient-e153138232031f82/5e30ad8/crates/build/src/lib.rs:38:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is there anything I can do to fix this? I just wanted to see what the examples looked like but they don't seem to build for me

**Comment by philpax** [comment]
Are you using the examples from the repository with Ambient 0.1.1? The main branch is used for development, so they're out of sync. If you'd like to check them out, you can either explicitly check out the 0.1.1 tag or download the examples from the release: https://github.com/AmbientRun/Ambient/releases/tag/v0.1.1

**Comment by hariria** [comment]
Ah i see, it might be helpful to clarify this in the README

> Each example in the [examples](https://github.com/AmbientRun/Ambient/blob/main/guest/rust/examples) directory can be run with Ambient as both client and server:

Could be better phrased as 
> Examples can be run from the v0.1.1 source code or examples assets in the [releases](https://github.com/AmbientRun/Ambient/releases). Choose an example and run `ambient run` to build and launch the example.

On a separate note, it seems like I'm still having issues running the tictactoe example (minigolf works, it seems like the examples with servers are the ones that aren't working for me). The error is the same as https://github.com/AmbientRun/Ambient/issues/198

**Comment by philpax** [comment]
Hm, good point about clarifying what people see from the README. I'll see what I can do.

> On a separate note, it seems like I'm still having issues running the tictactoe example (minigolf works, it seems like the examples with servers are the ones that aren't working for me). The error is the same as https://github.com/AmbientRun/Ambient/issues/198

Odd - so this is with a completely clean 0.1.1 runtime and examples? Can you show the commands you ran?

**Comment by chaosprint** [comment]
> 

I also encountered similar issue on M1 Mac when I tried to `ambient run` on the `physics` example at the latest version (v0.2 dev)

Neither `ambient run` (0.1.1) nor the latest one (v0.2 dev) can work with the latest example(v0.2 dev) `Tic Tac Toe` or `physics` .

## They have different errors

### `ambient run` (0.1.1) 
```
cargo install --git https://github.com/AmbientRun/Ambient.git --tag v0.1.1
```

Errors:
```
ambient run                                                                         ✔  took 3m 49s  at 04:11:49 PM 
[2023-03-19T15:21:07Z INFO  ambient] Building Physics
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: no compiler-artifact

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/backtrace.rs:332:13
   3: ambient_rustc::Rust::build
   4: ambient_build::build::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   7: tokio::runtime::runtime::Runtime::block_on
   8: ambient::main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: std::rt::lang_start::{{closure}}
  11: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/core/src/ops/function.rs:287:13
  12: std::panicking::try::do_call
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panicking.rs:487:40
  13: std::panicking::try
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panicking.rs:451:19
  14: std::panic::catch_unwind
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panic.rs:140:14
  15: std::rt::lang_start_internal::{{closure}}
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/rt.rs:148:48
  16: std::panicking::try::do_call
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panicking.rs:487:40
  17: std::panicking::try
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panicking.rs:451:19
  18: std::panic::catch_unwind
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panic.rs:140:14
  19: std::rt::lang_start_internal
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/rt.rs:148:20
  20: _main', /Users/chaosprint/.cargo/git/checkouts/ambient-e153138232031f82/5e30ad8/crates/build/src/lib.rs:38:55
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/core/src/result.rs:1750:5
   3: ambient_build::build::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   6: tokio::runtime::runtime::Runtime::block_on
   7: ambient::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### `ambient run` (0.2)
```
cargo install --git https://github.com/AmbientRun/Ambient.git ambient
```

Errors:
```
ambient run                                                                          ✔  at 04:04:52 PM 
[2023-03-19T15:04:53Z INFO  ambient] Building Tic Tac Toe
[2023-03-19T15:04:54Z INFO  ambient] Done building Tic Tac Toe
[2023-03-19T15:04:54Z INFO  ambient::server] Creating server
[2023-03-19T15:04:54Z INFO  ambient::server] Created server, running at 10.0.0.2:9000
[2023-03-19T15:04:54Z INFO  ambient::server] Starting server
thread 'main' panicked at '', /Users/chaosprint/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.14.1/src/metal/adapter.rs:485:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/4a04d086cac54a41517d5657b59d5fe2caca2d71/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
   3: wgpu_hal::metal::AdapterShared::new
   4: <wgpu_hal::metal::Instance as wgpu_hal::Instance<wgpu_hal::metal::Api>>::enumerate_adapters::{{closure}}
   5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   6: <wgpu_hal::metal::Instance as wgpu_hal::Instance<wgpu_hal::metal::Api>>::enumerate_adapters
   7: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter::gather
   8: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter
   9: wgpu::Instance::request_adapter
  10: ambient_gpu::gpu::Gpu::with_config::{{closure}}::{{closure}}
  11: ambient_app::AppBuilder::build::{{closure}}
  12: tokio::runtime::park::CachedParkThread::block_on
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  14: tokio::runtime::runtime::Runtime::block_on
  15: ambient::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
ambient(58375,0x10850c580) malloc: *** error for object 0x1: pointer being freed was not allocated
ambient(58375,0x10850c580) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ambient run
```

**Comment by hariria** [comment]
Yep i ran the same commands as @chaosprint

**Comment by chaosprint** [comment]
> Yep i ran the same commands as @chaosprint, interestingly though I did not have issues with the physics example

Aha, I think the latest version of `ambient run` at `v0.2.0-dev` should work fine on M1 Mac. At least I got it working on both the `Tic Tac Toe` and the `Physics` examples.

Try to install it again with:

```
cargo install --git https://github.com/AmbientRun/Ambient.git ambient
```

Then in your project, run:

```
cargo clean
```

Then it should work:
```
ambient run
```
