### ISSUE TITLE
The message from a `panic!("msg")` is missing from the console output

### ISSUE THREAD

**Issue by FredrikNoren** [AmbientRun/Ambient#306]
For a program that looks like this:

```rust
#[main]
pub async fn main() -> ResultEmpty {
    panic!("Hello, Ambient!");

    OkEmpty
}
```

I get the following output:
```sh
[2023-04-13T13:16:23Z INFO  ambient] Building infinibounce
[2023-04-13T13:16:24Z INFO  ambient] Done building infinibounce
[2023-04-13T13:16:24Z INFO  ambient::server] Creating server
[2023-04-13T13:16:24Z INFO  ambient::server] Created server, running at 192.168.0.5:9000
[2023-04-13T13:16:24Z INFO  ambient::server] Starting server
[2023-04-13T13:16:24Z INFO  ambient_network::server] Connecting to proxy server
[2023-04-13T13:16:24Z INFO  ambient_network::client] Connecting to server at 127.0.0.1:9000
[2023-04-13T13:16:24Z ERROR ambient::server::wasm] [server_infinibounce] error: Runtime error: error while executing at wasm backtrace:
        0: 0x2e38f - panic_abort::__rust_start_panic::abort::h4ef418136011ffa3
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/panic_abort/src/lib.rs:83:17              - __rust_start_panic
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/panic_abort/src/lib.rs:37:5
        1: 0x2e0f0 - rust_panic
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:736:9
        2: 0x2e0bf - std::panicking::rust_panic_with_hook::h911ba172265603df
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:706:5
        3: 0x2d345 - std::panicking::begin_panic_handler::{{closure}}::h7b07dd737a4d8757
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:577:13
        4: 0x2d2a7 - std::sys_common::backtrace::__rust_end_short_backtrace::ha54585d732ac30f6
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
        5: 0x2d93b - rust_begin_unwind
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
        6: 0x3323a - core::panicking::panic_fmt::h6958314cbbe045b2
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
        7:  0xcf5 - server_infinibounce::main_impl::{{closure}}::h63125c2f7f9dc3cf
                        at /Users/fredrik/github/infinibounce/src/server.rs:14:5
        8: 0x1184 - ambient_api::global::runtime::run_async::{{closure}}::h107701c0d67fa75f
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/global/runtime.rs:52:48
        9: 0x69fa - ambient_api::internal::executor::Executor::execute::{{closure}}::hf3ffb6eb66489099
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/executor.rs:100:27
       10: 0x2cb3 - alloc::vec::Vec<T,A>::retain_mut::process_loop::h0c3e035335d141d2
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/mod.rs:1642:21
       11: 0x3124 - alloc::vec::Vec<T,A>::retain_mut::h7882f5d68e70760c
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/mod.rs:1668:9
       12: 0x67c4 - ambient_api::internal::executor::Executor::execute::h9c94ba0d62e94aae
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/executor.rs:99:13
       13: 0x7b66 - <ambient_api::internal::Guest as ambient_api::internal::wit::guest::Guest>::exec::h0b0a43801fea060f
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/mod.rs:21:9
       14: 0x7ea2 - ambient_api::internal::wit::guest::call_exec::h28ab28f8d0c6b3e1
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/bindings.rs:7457:33
       15: 0x7f30 - guest#exec
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/bindings.rs:7495:35
    Root cause: wasm trap: wasm `unreachable` instruction executed
[2023-04-13T13:16:24Z WARN  ambient_core::async_ecs] Async run ran for 251ms
[2023-04-13T13:16:24Z ERROR ambient::server::wasm] [server_infinibounce] error: Runtime error: cannot reenter component instance
[2023-04-13T13:16:24Z ERROR ambient::server::wasm] [server_infinibounce] error: Runtime error: cannot reenter component instance
[2023-04-13T13:16:24Z INFO  ambient_network::server] [user_hdmMVmYz4wITFhWwCaUVb] Player spawned
[2023-04-13T13:16:24Z ERROR ambient::server::wasm] [server_infinibounce] error: Runtime error: cannot reenter component instance
[2023-04-13T13:16:24Z ERROR ambient::server::wasm] [server_infinibounce] error: Runtime error: cannot reenter component instance
[2023-04-13T13:16:24Z ERROR ambient::server::wasm] [server_infinibounce] error: Runtime error: cannot reenter component instance
[2023-04-13T13:16:24Z INFO  ambient::server::wasm] [server_infinibounce] info: Unloaded (reason: too many errors)
[2023-04-13T13:16:25Z INFO  ambient_network::server] Allocating proxy endpoint
[2023-04-13T13:16:25Z INFO  ambient_network::server] Proxy sees this server as 188.151.96.197:9000
[2023-04-13T13:16:25Z INFO  ambient_network::server] Proxy allocated an endpoint, use `ambient join proxy-eu.ambient.run:9409` to join
```

I.e. the string "Hello, Ambient" is missing in the console output.

**Comment by philpax** [comment]
I was going to mention the relevant code here but then I realised the fix was a lot simpler than I thought it was 😅

**Comment by FredrikNoren** [comment]
@philpax Here it's there now, but the formatting is a bit funky:

```sh
[2023-04-13T14:02:51Z INFO  ambient_network::server] Connecting to proxy server
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: thread '
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: <unnamed>
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: ' panicked at '
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: Hello, Ambient!
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: ',
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: src/server.rs
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: :
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: 27
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: :
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: 5
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: 
[2023-04-13T14:02:51Z INFO  ambient::server::wasm] [server_infinibounce] stderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-04-13T14:02:51Z ERROR ambient::server::wasm] [server_infinibounce] error: Runtime error: error while executing at wasm backtrace:
        0: 0x51ded - panic_abort::__rust_start_panic::abort::h4ef418136011ffa3
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/panic_abort/src/lib.rs:83:17              - __rust_start_panic
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/panic_abort/src/lib.rs:37:5
        1: 0x51b4e - rust_panic
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:736:9
        2: 0x51b1d - std::panicking::rust_panic_with_hook::h911ba172265603df
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:706:5
        3: 0x50da3 - std::panicking::begin_panic_handler::{{closure}}::h7b07dd737a4d8757
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:577:13
        4: 0x50d05 - std::sys_common::backtrace::__rust_end_short_backtrace::ha54585d732ac30f6
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
        5: 0x51399 - rust_begin_unwind
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
        6: 0x56c98 - core::panicking::panic_fmt::h6958314cbbe045b2
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
        7: 0x19de - server_infinibounce::main_impl::{{closure}}::h63125c2f7f9dc3cf
                        at /Users/fredrik/github/infinibounce/src/server.rs:27:5
        8: 0x2151 - ambient_api::global::runtime::run_async::{{closure}}::h107701c0d67fa75f
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/global/runtime.rs:52:48
        9: 0x10ba6 - ambient_api::internal::executor::Executor::execute::{{closure}}::hf3ffb6eb66489099
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/executor.rs:100:27
       10: 0x8c3b - alloc::vec::Vec<T,A>::retain_mut::process_loop::h0c3e035335d141d2
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/mod.rs:1642:21
       11: 0x90ac - alloc::vec::Vec<T,A>::retain_mut::h7882f5d68e70760c
                        at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/vec/mod.rs:1668:9
       12: 0x10970 - ambient_api::internal::executor::Executor::execute::h9c94ba0d62e94aae
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/executor.rs:99:13
       13: 0x1485b - <ambient_api::internal::Guest as ambient_api::internal::wit::guest::Guest>::exec::h0b0a43801fea060f
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/mod.rs:21:9
       14: 0x14cda - ambient_api::internal::wit::guest::call_exec::h28ab28f8d0c6b3e1
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/bindings.rs:7457:33
       15: 0x14d68 - guest#exec
                        at /Users/fredrik/.cargo/git/checkouts/ambient-e153138232031f82/844986c/guest/rust/api/src/internal/bindings.rs:7495:35
    Root cause: wasm trap: wasm `unreachable` instruction executed
[2023-04-13T14:02:51Z WARN  ambient_core::async_ecs] Async run ran for 219ms
```

**Comment by FredrikNoren** [comment]
@philpax Hm I see. Maybe pipe directly to stdout (instead of via the logging)? I guess then it would at least look ok, unless some other thread starts logging something in the middle of it.

**Comment by philpax** [comment]
I considered that, but then you'd lose the ability to know which module it came from. Maybe we should just assume that newlines are required for output and buffer away?
