### ISSUE TITLE
Panic when skinned mesh has a bone which drives a blend shape/morph target (GLTF and FBX)

### ISSUE THREAD

**Issue by alfredbaudisch** [AmbientRun/Ambient#371]
If a skinned mash has a bone that drives a blend shape / morph target, either GLTF or FBX, the asset is not imported.

The bone is keyframed only on `Location` and drives a blend shape value from 0 to 1.

https://user-images.githubusercontent.com/248383/236671476-e1d807ff-2da9-4f38-8ff4-bbc694d25d75.mp4

**GLTF Error**
```
thread 'tokio-runtime-worker' panicked at 'not implemented', <...>\7daa5ef\crates\model_import\src\gltf\mod.rs:109:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-05-07T10:13:10Z ERROR ambient_build] In pipeline pipeline.json/0, at file AnimationDriver.glb

    Caused by:
        task 30 panicked
```

**FBX Error**
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', crates\model_import\src\fbx\mesh.rs:115:108
[2023-05-07T10:13:10Z ERROR ambient_build] In pipeline pipeline.json/0, at file AnimationDriver.fbx

    Caused by:
        task 29 panicked
```

Tried to load in the `skinmesh` sample:

```rust
const START: (&str, &str) = (
    "GeradorLoop",
    "assets/AnimationDriver.glb/animations/TurnOnMachine.anim",
);
const END: (&str, &str) = ("GeradorTurnOn", "assets/AnimationDriver.glb/animations/TurnOnMachine.anim");

  let unit_id = Entity::new()
      .with_merge(make_transformable())
      .with(
          prefab_from_url(),
          asset::url("assets/AnimationDriver.glb").unwrap(),
      )
      .with(name(), "Moenda Motor".to_string())
      .spawn();
```

## Example
.blend, fbx and gltf reproduction sample: [AnimationDriveBlendShapeBone.zip](https://github.com/AmbientRun/Ambient/files/11414704/AnimationDriveBlendShapeBone.zip)

This mesh contains a very simple armature with one single bone that moves on the Y up and down, and drives the blend shape of this cube (from the sample GIF above).

**Comment by philpax** [comment]
Looked into this; it appears morph targets are not currently implemented. 

@FredrikNoren Looks like we need your input on this one, too. Are morph targets planned?

**Comment by FredrikNoren** [comment]
@philpax Not in the immediate future. @alfredbaudisch (or anyone else interested in it) if you'd like to take a stab at implementing morph targets we would be happy to review a PR for it.
