### ISSUE TITLE
ambient run Fails to attach to port on startup

### ISSUE THREAD

**Issue by kevzettler** [AmbientRun/Ambient#413]
I updated to latest master and ambient failing to attach to a port.

```
kevzettler@kevs-mbp-3 ambient-test-project % RUST_BACKTRACE=full ~/code/Ambient/target/release/ambient run
 INFO Building ambient-test-project
 INFO Done building ambient-test-project
 INFO Creating server
 WARN Failed to create server on port 9000
 WARN Failed to create server on port 9001
 WARN Failed to create server on port 9002
 WARN Failed to create server on port 9003
 WARN Failed to create server on port 9004
 WARN Failed to create server on port 9005
 WARN Failed to create server on port 9006
 WARN Failed to create server on port 9007
 WARN Failed to create server on port 9008
 WARN Failed to create server on port 9009
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to create game server with port in range

Caused by:
    Failed to create server

Stack backtrace:
   0: anyhow::backtrace::capture::Backtrace::capture
   1: anyhow::error::<impl anyhow::Error>::msg
   2: ambient::server::start::{{closure}}
   3: tokio::runtime::park::CachedParkThread::block_on
   4: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   5: tokio::runtime::runtime::Runtime::block_on
   6: ambient::server::start
   7: ambient::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
      std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
      std::panicking::try
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
      std::panic::catch_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  11: _main', app/src/server/mod.rs:75:14
stack backtrace:
   0:        0x10505c364 - std::backtrace_rs::backtrace::libunwind::trace::hf9c5171f212b04e2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10505c364 - std::backtrace_rs::backtrace::trace_unsynchronized::h179003f6ec753118
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10505c364 - std::sys_common::backtrace::_print_fmt::h92d38f701cf42b17
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10505c364 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb33e6e8152f78c95
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10507b14c - core::fmt::write::hd33da007f7a27e39
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:        0x105055e64 - std::io::Write::write_fmt::h7edc10723862001e
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:        0x10505c178 - std::sys_common::backtrace::_print::h5e00f05f436af01f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x10505c178 - std::sys_common::backtrace::print::h895ee35b3f17b334
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x10505da88 - std::panicking::default_hook::{{closure}}::h3b7ee083edc2ea3e
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:        0x10505d7e0 - std::panicking::default_hook::h4e7c2c28eba716f5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:        0x10505e0ac - std::panicking::rust_panic_with_hook::h1672176227032c45
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:        0x10505decc - std::panicking::begin_panic_handler::{{closure}}::h0b2d072f9624d32e
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:        0x10505c7cc - std::sys_common::backtrace::__rust_end_short_backtrace::he9abda779115b93c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x10505dc28 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:        0x1051c052c - core::panicking::panic_fmt::h23ae44661fec0889
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:        0x1051c084c - core::result::unwrap_failed::h414a6cbb12b1e143
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
  16:        0x102c53c34 - ambient::server::start::{{closure}}::h01d6f4908c1aa84a
  17:        0x102c4c510 - tokio::runtime::park::CachedParkThread::block_on::h6818f2d5daa28924
  18:        0x102a81548 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hea9b0ba6f78a8e71
  19:        0x1029477ac - tokio::runtime::runtime::Runtime::block_on::hb2c3f25301a1a87d
  20:        0x102c9320c - ambient::server::start::h482c60d2454b1331
  21:        0x102c96528 - ambient::main::hd362bcc7e20f77d2
  22:        0x102c5dcd0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc27433257560a412
  23:        0x102bb6c24 - std::rt::lang_start::{{closure}}::h42e58cea81f988c2
  24:        0x10504fde8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha1c2447b9b665e13
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  25:        0x10504fde8 - std::panicking::try::do_call::ha57d6d1e9532dc1f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  26:        0x10504fde8 - std::panicking::try::hca0526f287961ecd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  27:        0x10504fde8 - std::panic::catch_unwind::hdcaa7fa896e0496a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  28:        0x10504fde8 - std::rt::lang_start_internal::{{closure}}::h142ec071d3766871
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  29:        0x10504fde8 - std::panicking::try::do_call::h95f5e55d6f048978
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  30:        0x10504fde8 - std::panicking::try::h0fa00e2f7b4a5c64
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  31:        0x10504fde8 - std::panic::catch_unwind::h1765f149814d4d3e
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  32:        0x10504fde8 - std::rt::lang_start_internal::h00a235e820a7f01c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  33:        0x102c97c58 - _main
  ```

**Comment by kevzettler** [comment]
If I copy the localhost cert files to my project directory `cp ~/code/Ambient/localhost.* ./`  I can `run` again:

**Comment by FredrikNoren** [comment]
@ten3roberts This is fixed now right?

**Comment by ten3roberts** [comment]
The certs are bundled in non production environments (I.e not releases) as we currently have no good way to tell if the downloaded binary is used for the intents of development or playing on officially deployed game servers which require more security and using a bundled cert allows man in the middle attacks as the key is publicly known.

See this comment for more details: https://github.com/AmbientRun/Ambient/pull/414#issuecomment-1558946351

Do you have a good idea of how to go about this?

**Comment by FredrikNoren** [comment]
@ten3roberts Left a comment in the other thread

**Comment by ten3roberts** [comment]
@kevzettler can you confirm if this is fixed?

**Comment by kevzettler** [comment]
confirmed this is fixed in 7cdc71f7ec3780d45da0a126ae7f9ba03ec088a2
